services:
  redis:
    image: redis:latest
    container_name: rust-api-redis

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    ports:
      - "127.0.0.1:6379:6379"

    networks:
      - tasks-network

    restart: always

  postgres:
    image: postgres:18
    container_name: rust-api-postgres

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    environment:
      - POSTGRES_USER=<POSTGRES_USER>
      - POSTGRES_PASSWORD=<POSTGRES_PASSWORD>
      - POSTGRES_DB=ytc

    volumes:
      - /data/ytc/pgsql:/var/lib/postgresql

    networks:
      - tasks-network

    # ports:  # If you want to expose PostgreSQL to external connections
    #   - 5432:5432

    restart: always

networks:
  tasks-network:
    external: true

# Do : docker network create tasks-network
